name: solar system workflow

on: 
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature1'

jobs:
    unit-testing:
       name: unit testing
       strategy:
          matrix:
            nodejs_version: [18,19.20]
            operating_system: [ubuntu-latest,macos-latest]
            exclude:
                - nodejs_version: 18
                  operating_system: macos-latest

       runs-on: ${{ matrix.operating_system }}
       
       steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: setup nodejs
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.nodejs_version }}

        - name: dependency cache
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}


        - name: install dependiency
          run: npm install

        
